### PR TITLE
Sarah Kovan Assignment 2

### PR DESCRIPTION
**Pull request by SarahKovan**
https://jupyter.dartmouth.edu/user/f002c91/tree/Psych81.09/course/SarahKovan/storytelling-with-data/assignments/assignment%202/submissions/Kovan_Sarah

### CODE REVIEW

**Comment by jeremymanning** [comment]
Please add your notebook by running the following commands (from within your storytelling-with-data folder):
```
git add assignments/assignment\ 2/submissions/Kovan_Sarah
git commit -a -m "added assignment 2"
git push
git pull upstream master
git push
```

**Review by jeremymanning — CHANGES_REQUESTED** [review]
please revert changes on any file that's not related to your assignment submission.  for each file (replace `[filename]` with the relative path to the filename, e.g. `assignments/assignment\ 2/submissions/submission_instructions.md`, etc.):
```
git checkout origin/master [filename]
```

Then when you're done running that command for each file:

```
git commit -a -m "reverted course materials unrelated to assignment submission"
git push
```

**Comment by jeremymanning** [comment]
@SarahKovan let's try to get this pull request resolved.  let me know if you would like help...

**Comment by SarahKovan** [comment]
> @SarahKovan let's try to get this pull request resolved. let me know if you would like help...

Working on it now! What is the extra step beyond "git checkout origin/master" to move each file to its destination/how do I know the proper destination for each of the extra files I added?

**Comment by jeremymanning** [comment]
The solution we discussed in class is to copy the files you modified accidentally-- e.g. from `course/jeremy/storytelling-with data/...`

**Pull request merged**
