### PR TITLE
Assignment Four

### PR DESCRIPTION
**Pull request by AkiahW**

### CODE REVIEW

**Comment by jeremymanning** [comment]
@AkiahW it looks like your pull request conflicts with the request @alexwells-22 submitted.  Could the two of you address any conflicts (and/or close this request if it's redundant with alex's) and then ping me on slack so that I can merge them in?

**Review by jeremymanning — CHANGES_REQUESTED** [review]
added a comment on your pull request requesting some changes (need to address conflicts with @alexwells-22's request)

**Comment by alexwells-22** [comment]
I'm fairly certain that Akiah's files should be the most up-to-date version we have, but I'm not really sure how to resolve the conflicts

**Comment by AkiahW** [comment]
Yeah, my pull request should be the most up to date. Also not sure how to resolve and my lovely IT support is busy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
