### PR TITLE
aly berger file (in progress still)

### PR DESCRIPTION
**Pull request by alyberger**

### CODE REVIEW

**Comment by jeremymanning** [comment]
@alyberger do you want me to merge this, or are you still working on the assignment?

**Comment by alyberger** [comment]
Still working!

Sent from my iPhone

On Apr 9, 2019, at 9:08 PM, Jeremy Manning <notifications@github.com<mailto:notifications@github.com>> wrote:


@alyberger<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falyberger&data=02%7C01%7Calyssa.g.berger.19%40dartmouth.edu%7C4025f745d0094da9483508d6bd510f3a%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C636904553189860794&sdata=GfVuUwegGunWf%2F7pJ9MZeskZPy%2F3o21SZ42sJ1cIX%2FQ%3D&reserved=0> do you want me to merge this, or are you still working on the assignment?

**Review by jeremymanning — CHANGES_REQUESTED** [review]
please revert changes on `slides/data_visualization.ipynb`:
```
git checkout origin/master slides/data_visualization.ipynb
git commit -a -m "reverted data visualization notebook"
git push
```

**Comment by jeremymanning** [comment]
it looks like your README file is empty...

**Comment by alyberger** [comment]
Final pull request

**Review by jeremymanning — CHANGES_REQUESTED** [review]
Can you please revert the changes on the data_visualization slides?  One easy way to do this would be to download that file from the course repo and replace the copy in your repo, then commit and push the change (and this pull request should update automatically).

**Pull request merged**
