### PR TITLE
srowley assignment 2

### PR DESCRIPTION
**Pull request by soniarowley**
Folder containing: 
- Jupyter notebook for assignment titled 'rowley_sonia'
- 2 miscellaneous notebooks reflecting some of my work/experimentation
- 1 README.md file
- 1 dataset entitled education.csv

### CODE REVIEW

**Review by jeremymanning — CHANGES_REQUESTED** [review]
Please undo any changes to non-assignment files-- e.g. the rest of the course repository should be left untouched, and the only changes to the repository should be in your assignment submission folder.

**Comment by jeremymanning** [comment]
this is almost ready to merge-- but can you either move the education data file back to its original location (and update your notebook to reference that file), or create a copy of that file (one in the original location and another in your assignment folder)?

**Comment by soniarowley** [comment]
Okay, great! I just moved it. Let me know if there's anything else.

**Comment by jeremymanning** [comment]
did you push the change?

**Comment by soniarowley** [comment]
Oops, no. I just tried, and when I entered `git pull upstream master` I got this message: 

Screen Shot 2019-04-12 at 9 50 59 AM

When I type a "message" and hit enter, nothing happens.

**Comment by jeremymanning** [comment]
type `:q` and then enter

**Comment by soniarowley** [comment]
I'm very confused. Just committed my changes and it's saying I changed three of my classmates' files in addition to my own. I never even opened their files. I also can't figure out how to submit a pull request this time, even though I've done it without issue twice now.

**Comment by jeremymanning** [comment]
note: i'm guessing this is related to you calling `git pull upstream master`.  but we'll debug and figure this out...

**Pull request merged**
