### PR TITLE
Abigail, Athina, Nathan, Paxton, Tia UVLT analyses

### PR DESCRIPTION
**Pull request by paxtonfitzpatrick**
@jeremymanning let me know if you want me to look for and resolve the merge conflicts in this.

Also, it looks like one of the data stories from a previous year got deleted. Not sure how, but I can re-add  it

### CODE REVIEW

**Comment by jeremymanning** [comment]
@paxtonfitzpatrick if you could resolve the conflicts that would be fantastic!  There are a few I see:
- Some course files were moved or deleted
- The uvlt_explorations notebook was modified

**Comment by paxtonfitzpatrick** [comment]
@jeremymanning that should do it! Only difference in `slides/data_wrangling_with_pandas.ipynb` is execution count.

**Comment by jeremymanning** [comment]
Could you please also revert changes to uvlt_explorations?

**Comment by paxtonfitzpatrick** [comment]
good to go now. It says I missed a newline character, but I don't see it in the rendered notebook (and your MLPRegressor gained a few points haha)

**Comment by jeremymanning** [comment]
:+1:

**Pull request merged**
