### PR TITLE
hackathon 2

### PR DESCRIPTION
**Pull request by paxtonfitzpatrick**
Contributors: Paxton Fitzpatrick, Sonia Rowley, Athina Schmidt

### CODE REVIEW

**Comment by jeremymanning** [comment]
Can you resolve these conflicts?

**Comment by paxtonfitzpatrick** [comment]
Not sure why this file is counted as a conflict.  It's been moved to a subdirectory for the first hackathon project

**Comment by paxtonfitzpatrick** [comment]
Will it allow you to force the merge and just overwrite the base repo? The changes I see in that file are:
- base version has code for collapsable cells (jupyter extension I have on my computer, there because I pushed the last hackathon from my local machine)
- I added a space between a variable and an equals sign
- HTML code for inline folium map is different because it was re-run
- display name of kernel is different ("Psych 81.09" vs "Psych81.09").  Guessing this is a jupyter vs jupyter-dev thing.

I don't know which of these is creating the conflict

**Comment by jeremymanning** [comment]
I don't think I can....I think you need to pull the upstream changes into your fork and then deal with any conflicts there

**Comment by jeremymanning** [comment]
It's the violations-map notebook that's the issue

**Comment by paxtonfitzpatrick** [comment]
@jeremymanning I moved the file back to its location in the base repo, and that seems to have fixed the conflict...not sure why.  So just for clarity, `violations-map.ipynb` is part of our **first** hackathon assignment, not the 2nd.  It's just not in the `hackathon1` subdirectory because git didn't like it there.

**Comment by jeremymanning** [comment]
@paxtonfitzpatrick thanks, and thanks for the clarification.  could you use the `git mv` command to change where the file goes?  Or, as long as it's clear in some way which files go with which project I can do my best to make sense of it.  I'll merge this for now, though...

**Pull request merged**
