### PR TITLE
Create EA_AW_VermontDoH_datastory.ipynb

### PR DESCRIPTION
**Pull request by EmilyApp2**

### CODE REVIEW

**Comment by jeremymanning** [comment]
@EmilyApp2 it doesn't look like the notebook is actually a notebook file-- did you save it directly from Google Colaboratory?  Or did you try to manually paste in the contents?

**Comment by EmilyApp2** [comment]
I manually pasted in the contents. I will try to resave it from Colab now

**Comment by jeremymanning** [comment]
@EmilyApp2 can you ping me on slack, or tag me in a comment when you've updated your notebook?

**Review by jeremymanning — CHANGES_REQUESTED** [review]
(see comments on pull request)

**Pull request closed without merging**
